<p class="c1 c11 c8"><span class="c3"></span></p><p class="c6"><span class="c16 c10"><b>ACTIVAR RUBROS</b></span></p>
<br/>
<ul>
<p class="c1"><span class="c0">El responsable de farmacia o la UGPFDMPS podrá activar aquellos rubros tanto de medicamentos como de dispositivos médicos que hayan sido cerrados por el responsable que tenga el registro del rubro.</span></p>
<br/>

<p class="c1"><span class="c3"><b>Medicamentos:</b></span></p>
<br/>
<p class="c1"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 416.00px; height: 145.00px;"><img alt="" src="https://lh6.googleusercontent.com/xNMwVHK44v8t1hCl21ryhXRc2kPXyX1Dexfd6Z0s4P7jGgsbRUAm7lqhL-o6A-TOGVblfRtQvXt_Dt4vDqEhT3kFuii70kpVoFOCWLNmg7ex9eGWKOZO_ZEPbriEDkSi2gj7xVA67NUP1PY07w" style="width: 416.00px; height: 168.00px; margin-left: -0.00px; margin-top: -11.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
<p class="c1 c8"><span class="c3"></span></p><p class="c1 c8"><span class="c3"></span></p><p class="c1 c8"><span class="c3"></span></p><p class="c1 c8"><span class="c3"></span></p>
<br/>
<p class="c1"><span class="c0">En la columna de Descripción, aparecerán los rubros activos. Haciendo clic en el enlace, se nos abrirá otra ventana la cual nos mostrara la opción de desmarcar el Medicamento Cerrado haciendo clic en el check  permitirá nuevamente al RUBRO para hacer la edición.</span></p>
<br/>
<p class="c1"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 321.00px; height: 120.92px;"><img alt="" src="https://lh5.googleusercontent.com/THqBxJTIZERxyBulx9wr-qT_4a7AymrTkhmt6U_MSKRYm6KD0y99NiQWJVRahHh2XHn1KIXn9tpsB2Nd4-ZAkReA9KKhoOmw49RcHslZyZweQRXRGaJj60Ul1XNWhBq4jTmQ1orGPibWpQhgqA" style="width: 321.00px; height: 126.92px; margin-left: -0.00px; margin-top: -6.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
<br/>
<p class="c1"><span class="c10"><b>Dispositivos</b></span><span class="c0">.</span></p><p class="c1"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 509.00px; height: 163.00px;"><img alt="" src="https://lh5.googleusercontent.com/XEJR71peI7jqt0MiMbb3YgzTq8rslWtfB_INNiv4GPNaitHEgjwxug7zKE9sh5y1ublkuzgWOSM98f6_lI35q3lATdGtP0esAziStURKUHHyurcDmNtpe8NSjmVA48RZIKJnx6D1g01FMOdmDg" style="width: 509.00px; height: 182.00px; margin-left: -0.00px; margin-top: -19.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
<br/>
<p class="c1"><span class="c0"> En la columna de Descripción, aparecerán los rubros activos. Haciendo clic en el enlace, se nos abrirá otra ventana la cual nos mostrara la opción de desmarcar el Dispositivo Medico Cerrado haciendo clic en el check  permitirá nuevamente al RUBRO para hacer la edición.</span>
</p>
<p>
<span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 333.00px; height: 130.87px;"><img alt="" src="https://lh3.googleusercontent.com/9mYGarJ9eejiJ8tjiIrWxh78XyfvQ5ffHWITBrghxpIxZI5RyTeIzjqVSQ6HqZcD0Qacyk0U3mTKM_7t53FtPbhuFYDlsRmBp2JAkdQLuy2KQwSBb1L9a8XP18nVEF1pXbIHvSAsqo24vJ6H8g" style="width: 333.00px; height: 130.87px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c1 c8"><span class="c0"></span></p><p class="c1 c8"><span class="c0"></span></p><p class="c1 c8"><span class="c0"></span></p><p class="c1 c8"><span class="c0"></span></p><p class="c1 c8"><span class="c0"></span></p><p class="c1 c8"><span class="c0"></span></p>
<br/>
<p class="c1"><span class="c0">Si ambos están cerrados  también se pueden activar para su edición.</span></p><p class="c1"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 404.95px; height: 210.97px;"><img alt="" src="https://lh4.googleusercontent.com/PF142AWfFNXZ7c9Ogmepwp_hYf6ST2a4bSyUfHeUXlQrEcUlNVfhfy72uocEUdm-hA5iXSIzY2pkiWxS2LVL0XNnayv0yv_jmm1pqWX_R3V5SEl1U7LALmXvGBrWnfW75zHAlBmrsC07Ki3MXA" style="width: 404.95px; height: 210.97px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><hr style="page-break-before:always;display:none;"><p class="c1 c8"><span class="c0"></span></p>
</ul>