<ul>
	<p class="c0"><span class="c5"></span></p><p class="c8"><span class="c16 c1"><b>LISTAR CAN</b></span></p>
	<br/>
	<p class="c2"><span class="c5">Después de autenticarse observaremos la siguiente ventana, la cual podemos observar lo siguiente:</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.00px; height: 214.33px;">
		<br/>
		<img alt="" src="https://lh4.googleusercontent.com/ydqDpBdDfArOs-uHsPKTfIBgCqMYFwbCOndMAI4YGlWgu9x3djtgosdIj_KQAI2g8P_kzXe4J4bmOq_36D3nnjC6H66mQtkNWs25jsjax8Azpzb1rmwdMxX-BnvuaFTnRygQuy5hkZ0DLP2eGQ" style="width: 720.00px; height: 214.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0"><span class="c5"></span></p><p class="c2"><span class="c1"><b>1.- NÚMERO DE ENTRADA:</b></span><span class="c5"> Se selecciona el número de registros CAN que podemos visualizar en cada página. </span>
	<br/><br/>
			

			<img alt="" src='{{ asset ("/images/image2.jpg") }}' title=""></p><p class="c8 c4"><span class="c5"></span></p><p class="c0"><span class="c5"></span></p><p class="c0"><span class="c6 c1"></span></p><p class="c2"><span class="c1"><b>2.- BUSCAR: </b></span><span class="c5">Es una caja de texto la cual podemos hacer la búsqueda de los CAN registrados. A medida que se ingrese carácter por carácter se ira filtrando la correspondencia del texto ingresado. </span></p>
	<br/>
			<p class="c2"><span class="c1"><b>3.- NÚMERO DE REGISTROS:</b> </span><span>Es el número de CAN registrado</span></p>
	<br/>
	<p class="c2"><span class="c1"><b>4.- PAGINACION: </b></span><span>Mostrara las paginaciones</span><span class="c1"> </span><span>dependiendo del número de entradas seleccionadas</span></p>
</ul>
<br/>
<hr>
<ul>
<p class="c2"><span class="c0">La Primera vez que ingresamos a visualizar se mostrará lo siguiente.</span></p><p class="c1"><span class="c0"></span></p><p class="c2"><img alt="" src='{{ asset ("/images/img_01.png") }}' style="width: 80%; height: 80%; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></p>
<br/>
<p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">En la parte superior se muestra el consolidado de la IPRESS, esto quiere decir que todo el registro realizado por farmacia y almacén se verá reflejado aquí.</span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">Es muy importante recordar que ambos responsable(Farmacia y Almacén) llenaran sus respectivos registros; y si aún no se han terminado su registros, estos iconos no se habilitarán para su visualización y/o descarga.</span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 592.50px; height: 132.27px;"><img alt="" src='{{ asset ("/images/img_02.png") }}' style="width: 812.49px; height: 287.48px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
<br/>
<p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">Igual manera Pasa en la parte del listado de responsables, si no se ha cerrado el petitorio de uno de los responsable sea de medicamentos o dispositivos médicos, no podrá ser visualizado.</span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 592.18px; height: 130.50px;"><img alt="" src='{{ asset ("/images/img_03.png") }}' style="width: 660.18px; height: 233.58px; margin-left: 0.00px; margin-top: -103.08px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c1"><span class="c0"></span></p>
<br/>
<p class="c1"><span class="c0"></span></p><p class="c1"><span class="c0"></span></p><p class="c1"><span class="c0"></span></p><hr style="page-break-before:always;display:none;"><p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">Si ya han empezado a cerrar petitorio los responsables de Farmacia y/o Almacén, deberá de habilitarse el icono de medicamentos o dispositivos médicos, tal como se muestra en la siguiente ventana.</span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 198.67px;"><img alt="" src='{{ asset ("/images/img_04.png") }}' style="width: 602.00px; height: 198.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
<br/>
<p class="c2"><span class="c0">Por ejemplo observamos que el Responsable de Almacén ya cerró Medicamentos pero no Dispositivos Médicos, de igual forma el Responsable de Farmacia ya cerró Dispositivos Médicos pero no Medicamentos.</span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">Pero si observamos en la parte del Consolidado aún no se habilitan los iconos. Esto significa que aún no han coincidido los responsables en el cerrado un determinado rubro.</span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 605.50px; height: 124.94px;"><img alt="" src='{{ asset ("/images/img_05.png") }}' style="width: 826.56px; height: 273.23px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c1"><span class="c0"></span></p><hr style="page-break-before:always;display:none;"><p class="c1"><span class="c0"></span></p>
<br/>
<p class="c2"><span>En la siguiente ventana observamos lo siguiente:</span>
</p>
<p>
<span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 630.50px; height: 218.89px;"><img alt="" src='{{ asset ("/images/img_06.png") }}' style="width: 630.50px; height: 218.89px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
<br/>
<p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">Nos muestra         que ya podrá visualizar los productos  de medicamentos</span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 633.06px; height: 132.50px;"><img alt="" src='{{ asset ("/images/img_07.png") }}' style="width: 860.27px; height: 297.77px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
<br/>
<p class="c1"><span class="c0"></span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">En el listado vemos que ya cerró tanto almacén y farmacia medicamentos; pero falta cerrar almacén (dispositivo médico) para que se habilita la opción del icono del consolidado.</span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 638.00px; height: 101.50px;"><img alt="" src='{{ asset ("/images/img_08.png") }}' style="width: 699.59px; height: 241.06px; margin-left: 0.00px; margin-top: -102.65px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c1"><span class="c0"></span></p>
<br/>
<p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">Al final su CAN deberia quedar algo como asi.</span></p><hr style="page-break-before:always;display:none;"><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 166.67px;"><img alt="" src='{{ asset ("/images/img_09.png") }}' style="width: 602.00px; height: 166.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c1"><span class="c0"></span></p>
<br/>
<p class="c2"><span class="c0">Cuando ya se han habilitado los iconos se podrá ingresar a ver los productos que llenó farmacia y que lleno almacen </span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">En la parte superior derecha podrá descargar el contenido de su CAN, tanto en PDF como en EXCEL.</span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 234.67px;"><img alt="" src='{{ asset ("/images/img_10.png") }}' style="width: 602.00px; height: 234.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c1"><span class="c0"></span></p><p class="c1"><span class="c0"></span></p>
<br/>
<p class="c1"><span class="c0"></span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 241.33px;"><img alt="" src='{{ asset ("/images/img_11.png") }}' style="width: 602.00px; height: 241.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c1"><span class="c0"></span></p><hr style="page-break-before:always;display:none;">
<br/>
<p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">Cuando se ingresa a la opción del  Consolidado en los iconos ya activos, se visualizarán los productos agrupados (Solo para productos de ambos uso).</span></p><p class="c1"><span class="c0"></span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 90%; height: 90%;"><img alt="" src='{{ asset ("/images/img_12.png") }}' style="width: 70%; height: 70%; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
<br/>
<p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">Aquí aparecerá en la parte izquierda un icono para visualizar quien ha llenado dicho producto.</span></p><p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 90%; height: 90%;"><img alt="" src='{{ asset ("/images/img_13.png") }}' style="width: 70%; height: 70%; margin-left: -63.64px; margin-top: -93.10px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c1"><span class="c0"></span></p>
<br/>
<p class="c2"><span class="c0">Al hacer clic en el icono aparecerá esta ventana emergente.</span></p><p class="c2"><img alt="" src='{{ asset ("/images/img_14.png") }}' title=""></p><p class="c1"><span class="c0"></span></p>
<br/>
<p class="c1"><span class="c0"></span></p><p class="c2"><span class="c0">Si todo corresponde descargar el archivo en pdf para ser firmado por el responsable de la IPRESS, Farmacia y/o Almacén.</span></p></div>
</ul>