<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 141.18px; height: 212.50px;"><img alt="" src='{{ asset ("/images/image24.jpg") }}' style="width: 141.18px; height: 212.50px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<br/>
		<br/>
		<p class="c0"><b><span class="c2">LISTAR: </span></b><span class="c1">Ubicado en la parte izquierda, al momento de hacer clic, nos lleva a visualizar todos los ICI registrados. En esta pantalla podemos ver el detalle de los registros llevados en el mes, usted podr&aacute; ingresar y ver su informaci&oacute;n.</span></p>
		<br/>
		<p class="c0"><span>A continuaci&oacute;n se muestra las opciones que se pueden usar al momento de ingresar al aplicativo.</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 802.00px; height: 171.33px;"><img alt="" src='{{ asset ("/images/image21.jpg") }}' style="width: 802.00px; height: 171.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<br/><br/>
		<p class="c0"><span class="c1">Existen 6 columnas para visualizar su ICI.</span></p>
		<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 802.00px; height: 353.33px;"><img alt="" src='{{ asset ("/images/image27.jpg") }}' style="width: 802.00px; height: 353.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<br/><br/>
		<p class="c0"><span class="c2"><b>MES: </b></span><span class="c1">Ordenado por ingreso de registro del ICI, se listar&aacute; o mostrar&aacute; en forma descendente es decir, al principio se ver&aacute; el &uacute;ltimo ICI activo que se puede editar. </span></p>
		<p class="c0"><span class="c1">Todos los 1 de cada mes se habilitar&aacute; el ICI del mes anterior, para ser editado.</span></p>
		<p class="c0"><span class="c1">A medida que van llenando se ir&aacute;n registrando sus ICI, la cual usted tendr&aacute; a la mano informaci&oacute;n al instante de sus movimientos de medicamentos/dispositivos m&eacute;dicos. </span></p>
		<br/>
		<p class="c0"><span class="c2"><b>A&Ntilde;O: </b></span><span class="c1">Lista los a&ntilde;os que pertenece cada mes, con el que se ha ido llenando. &nbsp;</span></p>
		<br/>
		<p class="c0"><span class="c2"><b>MEDICAMENTO: </b></span><span class="c1">Muestra el estado de registro de medicamentos estos 2 estados, servir&aacute;n para el control respectivo de su llenado, el primer estado uno de color verde &ldquo;Abierto&rdquo; que significa que puede editar y registrar su ICI, el &nbsp;otro estado es de color rojo &ldquo;Cerrado&rdquo; que significa que ya no se puede registrar. Para volver a editar, se tendr&aacute; que hacer una llamada al administrador del sistema para su habilitaci&oacute;n. </span></p><hr style="page-break-before:always;display:none;">
		<p class="c0 c4"><span class="c5 c2"></span></p>
		<br/>
		<p class="c0"><span class="c2"><b>DISPOSITIVO:</b> </span><span class="c1">Muestra el estado de registro de dispositivos m&eacute;dicos estos 2 estados, servir&aacute;n para el control respectivo de su llenado, el primer estado uno de color verde &ldquo;Abierto&rdquo; que significa que puede editar y registrar su ICI, el &nbsp;otro estado es de color rojo &ldquo;Cerrado&rdquo; que significa que ya no se puede registrar. Para volver a editar, se tendr&aacute; que hacer una llamada al administrador del sistema para su habilitaci&oacute;n. </span></p><br/>
		<p class="c0"><span class="c2"><b>N&deg; ATENCIONES: </b></span><span class="c1">Es el n&uacute;mero de atenciones que su Hospital/Cl&iacute;nica/Policl&iacute;nico/Posta M&eacute;dica/Puesto Sanitario ha realizado en el mes. </span></p>
		<p class="c0"><span class="c1">Cuando esta de color Azul, significa que se puede editar las veces que se desea, esta opci&oacute;n queda deshabilitado una vez se haya cerrado el ICI tanto de medicamentos como de dispositivos, Si aun esta cerrado Medicamentos o Dispositivo esta opci&oacute;n a&uacute;n aparecer&aacute;, hasta que se cierre ambos.</span></p>
		<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 162.50px; height: 63.19px;"><img alt="" src='{{ asset ("/images/image16.jpg") }}' style="width: 776.39px; height: 63.19px; margin-left: -473.31px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<p class="c0"><span class="c2"><b>DESCARGAR: </b></span><span class="c1">Muestra 2 botones con iconos referente tanto de Medicamento como Dispositivo, las cuales el ICI se puede descargar tanto del registro de medicamentos como de dispositivos m&eacute;dicos, al igual que la columna de medicamentos/dispositivo muestra 2 estados, Botones Inhabilitado, que significa que aun se esta llenando el ICI, Y botones Habilitado, que significa que ya cerr&oacute; el ICI.</span></p>
		<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 101.50px; height: 90.88px;"><img alt="" src='{{ asset ("/images/image6.jpg") }}' style="width: 101.50px; height: 90.88px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<hr style="page-break-before:always;display:none;">
		<p class="c0 c4"><span class="c1"></span></p><br/>
		
		