		<p class="c0"><b><span class="c2">EDITAR</span></b><span class="c1">&nbsp;</span></p>
		<p class="c0"><span class="c1">Se podr&aacute; actualizar o registrar un medicamento/dispositivo, haciendo clic en el boton de edestimacionon ubicado al lado izquierdo de la descripci&oacute;n.</span></p><p class="c0"><span class="c1">&nbsp;Aqui aparecera una ventana emergente, la cual podr&aacute; ser trabajada.</span></p><p class="c0"><span>A diferencia del formulario de </span><span class="c2">&ldquo;Nuevo&rdquo;, no se podr&aacute; editar los campos &ldquo;Nombre del medicamento&rdquo;, &ldquo;CPMA&rdquo; y &ldquo;Stock Inestimacional&rdquo;</span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 321.33px;"><img alt="" src='{{ asset ("/images/image1.jpg") }}' style="width: 602.00px; height: 321.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		

		<p class="c0"><span class="c2"><b>1.- Nombre del Medicamento/Dispositivo M&eacute;dico:</b></span><span class="c1">&nbsp;Esta opci&oacute;n visualiza el producto a editar. El campo esta inhabilitado, es decir no puede ser editado</span></p>
		<p class="c0"><span class="c2"><b>2.- CPMA:</b></span><span class="c1">&nbsp;El Consumo Promedio Mensual Ajustado, es la cantidad que se debe colocar obligatoriamente, y corresponde al consumo promedio que ha tenido cierto medicamento/dispositivo m&eacute;dico en los &uacute;ltimos 6 meses. Este campo debe de ser mayor a cero.  Este campo recoge el CPMA ingresado anteriormente. Esta opción esta inhabilitada</span></p>
		<p class="c0"><span class="c2"><b>3.- Stock Inestimacional:</b></span><span>&nbsp;Es la cantidad de medicamento/dispositivo que tiene actualmente en su farmacia. Este campo recoge del Stock Final del mes anterior. Este campo esta inhabilitado.</span></p>
		<p class="c0"><span class="c2"><b>4.- Ingreso de Almac&eacute;n central Saludpol:</b></span><span class="c1">&nbsp;Es la cantidad que se debe ingresar cuando se ha retirado medicamento/dispositivo del propio almac&eacute;n de saludpol. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>5.- Ingreso de su Almac&eacute;n: </b></span><span class="c1">Es la cantidad de medicamento/dispositivo que ha sido retirado de su propio almac&eacute;n ubicado en la misma instituci&oacute;n. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>6.- Ingreso directo del Proveedor: </b></span><span class="c1">Es la cantidad de medicamentos/dispositivos m&eacute;dicos que un Proveedor distinto a Saludpol deja los productos a su farmacia. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>7.- Ingreso por transferencia: </b></span><span>Es la cantidad de medicamentos/dispositivos m&eacute;dicos que se hace entre farmacias o entre ipress a nivel nacional.</span><span class="c2">&nbsp;</span><span>Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>8.- Unidad de Consumo: </b></span><span class="c1">Es la cantidad que tiene un medicamento/dispositivo m&eacute;dico al ser retirado de farmacia por prescripci&oacute;n m&eacute;dica. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>9.- Salida por transferencia:</b></span><span class="c1">&nbsp;Es la cantidad de un producto/medicamento al ser transferido o llevado a otra farmacia o ipress. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>10.- P&eacute;rdida/Merma: </b></span><span class="c1">Es la cantidad de medicamentos que han sido vencidos, o han sufrido alg&uacute;n da&ntilde;o en su composestimacion&oacute;n. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>11.- Fecha de Vencimiento:</b></span><span class="c1">&nbsp;Es la fecha a vencer del medicamento/dispositivo m&eacute;dico. La fecha es obligatoria, sino hubiese ninguna indicaci&oacute;n en dicho producto, a criterio personal colocar dicho valor.</span></p>
		
		<p class="c0"><span class="c1">Si la cantidad de ingreso es mayor que la cantidad de salida, nos mostrar&aacute; el siguiente mensaje.</span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 214.67px;"><img alt="" src='{{ asset ("/images/image26.jpg") }}' style="width: 602.00px; height: 214.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 441.00px; height: 117.00px;"><img alt="" src='{{ asset ("/images/image19.jpg") }}' style="width: 441.00px; height: 117.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0"><span class="c1">Al finalizar la actualizaci&oacute;n y presionar el bot&oacute;n de guardar aparecer&aacute; un mensaje que se ha actualizado con &eacute;xito</span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 228.00px;"><img alt="" src='{{ asset ("/images/image14.jpg") }}' style="width: 602.00px; height: 300.00px; margin-left: 0.00px; margin-top: -72.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0"><span class="c1">Una vez que se ha completado el registro, se podr&aacute; cerrar el petitorio tanto para medicamentos como para dispositivos m&eacute;dicos. </span></p><hr style="page-break-before:always;display:none;"><p class="c0 c4"><span class="c2 c5"></span></p>
		<br/>

