		<p class="c0"><span class="c5 c2"><b>MEDICAMENTOS/DISPOSITIVOS M&Eacute;DICOS.</b></span></p>
		<p class="c0"><b><span class="c2">Nota:</span><span>&nbsp;</span><span class="c8 c2 c9">Si a&uacute;n no hemos llenado el n&uacute;mero de atenciones en el mes, no se podr&aacute; visualizar esta ventana, y aparecer&aacute; la ventana para registrar las atenciones, una vez llenado, reci&eacute;n podemos llenar el ICI tanto de medicamentos, como de dispositivos m&eacute;dicos.</span></b></p>
		<p class="c0"><span>Al momento de ingresar a esta opci&oacute;n podemos visualizar la siguiente ventana. Aqu&iacute; se cargar&aacute; la informaci&oacute;n que se registro el mes anterior con los medicamentos/dispositivos que a&uacute;n tiene en stock. </span><span class="c2 c8">Es decir est&aacute; jalando el stock final del mes anterior, y se le esta asignando al stock inestimacional, la cual no podr&aacute; ser editado. </span><span class="c7">No aparecen los medicamentos/dispositivos con stock cero.</span></p>
		<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 393.33px;"><img alt="" src='{{ asset ("/images/image8.jpg") }}' style="width: 602.00px; height: 393.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 111.50px; height: 94.67px;"><img alt="" src='{{ asset ("/images/image8.jpg") }}' style="width: 1266.47px; height: 826.78px; margin-left: -875.17px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<br/>
		<p class="c0"><span class="c2"><b>Nuevo: </b></span><span class="c1">Esta opci&oacute;n nos permite agregar medicamentos/dispositivos m&eacute;dicos que no aparecen en la lista de abajo, por alg&uacute;n motivo el aplicativo no lo ha tomado en cuenta, si tenia stock cero, o ha ingresado un nuevo producto a su farmacia y desea ser a&ntilde;adido para el registro.</span></p><p class="c0 c4"><span class="c1"></span></p>
		<p class="c0"><span class="c1">Dicha opci&oacute;n nos permite agregar un medicamento/dispositivo m&eacute;dico de su nivel de establecimiento de salud, es decir, si su establecimiento pertenece al nivel 1, aparecer&aacute;n los medicamentos/dispositivos del nivel 1, si pertenece al nivel 2 aparecer&aacute;n del nivel 2 y si pertenece al nivel 3 aparecer&aacute;n del nivel 3. No permite visualizar medicamentos/dispositivos que ya han sido registrado o que aparecen en el listado.</span></p>
		<p class="c0"><span>Clic en el bot&oacute;n </span><span class="c5 c2">Nuevo.</span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 314.67px;"><img alt="" src='{{ asset ("/images/image23.jpg") }}' style="width: 602.00px; height: 314.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<p class="c0"><span class="c2"><b>1.- Nombre del Medicamento/Dispositivo M&eacute;dico:</b></span><span class="c1">&nbsp;Esta opci&oacute;n visualiza los productos correspondiente tanto a medicamentos como a dispositivos m&eacute;dicos.</span></p>
		<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 422.00px; height: 293.00px;"><img alt="" src='{{ asset ("/images/image4.jpg") }}' style="width: 422.00px; height: 293.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<p class="c0"><span class="c2"><b>2.- CPMA:</b></span><span class="c1">&nbsp;El Consumo Promedio Mensual Ajustado, es la cantidad que se debe colocar obligatoriamente, y corresponde al consumo promedio que ha tenido cierto medicamento/dispositivo m&eacute;dico en los &uacute;ltimos 6 meses. Este campo debe de ser mayor a cero.</span></p>
		<p class="c0"><span class="c2"><b>3.- Stock Inestimacional:</b></span><span>&nbsp;Es la cantidad de medicamento/dispositivo que tiene actualmente en su farmacia. Este campo debe ser mayor a cero.</span></p>
		<p class="c0"><span class="c2"><b>4.- Ingreso de Almac&eacute;n central Saludpol:</b></span><span class="c1">&nbsp;Es la cantidad que se debe ingresar cuando se ha retirado medicamento/dispositivo del propio almac&eacute;n de saludpol. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>5.- Ingreso de su Almac&eacute;n: </b></span><span class="c1">Es la cantidad de medicamento/dispositivo que ha sido retirado de su propio almac&eacute;n ubicado en la misma instituci&oacute;n. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>6.- Ingreso directo del Proveedor: </b></span><span class="c1">Es la cantidad de medicamentos/dispositivos m&eacute;dicos que un Proveedor distinto a Saludpol deja los productos a su farmacia. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>7.- Ingreso por transferencia: </b></span><span>Es la cantidad de medicamentos/dispositivos m&eacute;dicos que se hace entre farmacias o entre ipress a nivel nacional.</span><span class="c2">&nbsp;</span><span>Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>8.- Unidad de Consumo: </b></span><span class="c1">Es la cantidad que tiene un medicamento/dispositivo m&eacute;dico al ser retirado de farmacia por prescripci&oacute;n m&eacute;dica. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>9.- Salida por transferencia:</b></span><span class="c1">&nbsp;Es la cantidad de un producto/medicamento al ser transferido o llevado a otra farmacia o ipress. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>10.- P&eacute;rdida/Merma: </b></span><span class="c1">Es la cantidad de medicamentos que han sido vencidos, o han sufrido alg&uacute;n da&ntilde;o en su composestimacion&oacute;n. Si no tiene movimiento dejar en cero.</span></p>
		<p class="c0"><span class="c2"><b>11.- Fecha de Vencimiento:</b></span><span class="c1">&nbsp;Es la fecha a vencer del medicamento/dispositivo m&eacute;dico. La fecha es obligatoria, sino hubiese ninguna indicaci&oacute;n en dicho producto, a criterio personal colocar dicho valor.</span></p>
		<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 271.85px; height: 195.50px;"><img alt="" src='{{ asset ("/images/image28.jpg") }}' style="width: 271.85px; height: 195.50px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<p class="c0"><b><span class="c2 c6">Nota: La suma de ingreso no debe ser menor a los movimientos de salida, no est&aacute; permitido valores vac&iacute;os.</span></b>
			<span class="c1">&nbsp;</span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 377.00px; height: 85.00px;"><img alt="" src='{{ asset ("/images/image25.jpg") }}' style="width: 377.00px; height: 85.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0 c4"><span class="c1"></span></p>
		<p class="c0 c4"><span class="c1"></span></p><p class="c0 c4"><span class="c1"></span></p>
		<p class="c0"><span class="c1">Usted podr&aacute; visualizar si su medicamento/dispositivo a sido ingresado correctamente. Al final del listado podr&aacute; visualizar la cantidad de medicamento/dispositivo que se tiene.</span></p>
		<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 360.50px; height: 432.82px;"><img alt="" src='{{ asset ("/images/image11.jpg") }}' style="width: 360.50px; height: 432.82px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
		<p class="c0"><span class="c1">Al momento del registro de un nuevo medicamento. Y hacer clic en el bot&oacute;n de guardar, nos llevar&aacute; nuevamente a la ventana &nbsp;anterior.</span></p>
		<p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 602.00px; height: 296.00px;"><img alt="" src='{{ asset ("/images/image3.jpg") }}' style="width: 602.00px; height: 296.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0 c4"><span class="c1"></span></p><p class="c0"><span>Aqu&iacute; se visualiza el nuevo medicamento/dispositivo m&eacute;dico ingresado correctamente, adem&aacute;s de visualizar el nuevo conteo de registro.</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 352.50px; height: 339.16px;"><img alt="" src='{{ asset ("/images/image12.jpg") }}' style="width: 352.50px; height: 339.16px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
